### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by lego-yaw** [oboforty/metafetcher#6]
i was confronted by this error during installation, can you kindly help

Downloading GitHub repo komorowskilab/metafetcher@HEAD
Skipping 1 packages not available: hfun
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\yawyo\AppData\Local\Temp\RtmpGiPmDb\remotes6dc4394347d8\komorowskilab-metafetcher-d915ed2/DESCRIPTION' (454ms)
─  preparing 'metafetcher':
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'metafetcher_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/yawyo/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependency 'hfun' is not available for package 'metafetcher'
* removing 'C:/Users/yawyo/AppData/Local/R/win-library/4.2/metafetcher'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/yawyo/AppData/Local/Temp/RtmpGiPmDb/file6dc442fd3980/metafetcher_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by hh1985** [comment]
Same issue here. No idea where to find the `hfun` package. @oboforty @SaraYones

**Comment by SaraYones** [comment]
Hello,
please use
library(devtools)
install_github("shizidushu/hfun","komorowskilab/metafetcher")


I suggest you remove the installation that you did for metafetcher and you reinstall it using this 

library(devtools)
install_github("shizidushu/hfun","komorowskilab/metafetcher")

Please let us know if this resolves your problem

**Comment by hh1985** [comment]
@SaraYones I can now successfully install metafetcher. Thx a lot!

**Comment by SaraYones** [comment]
Great :) then i will close this issue
